import { Router } from "express";
import flieUpload, { fileType } from "../../utls/multer.js";
import * as CtegoryController from "./category.controller.js";
import { auth } from "../../middlewave/auth.js";
import subcategoryRouter from "../subcategory/subcategory.router.js";
import { endPoint } from "./category.role.js";
import { asyncHandler } from "../../utls/catchError.js";
import { validation } from "../../middlewave/validation.js";
import * as schema from "./category.validation.js";
const router = Router({caseSensitive:true});
router.use('/:id/subcategories',asyncHandler(subcategoryRouter));
router.post('/',flieUpload(fileType.image).single('image'),validation(schema.createCategorySchema),auth(endPoint.Create),asyncHandler(CtegoryController.CreateCategory));
router.get('/ActiveCategory',asyncHandler(CtegoryController.getActive));
router.get('/',auth(endPoint.getAll),asyncHandler(CtegoryController.getAll));
router.get('/:id',validation(schema.getCategorySchema),auth(endPoint.getDetails),asyncHandler(CtegoryController.getDetails));
router.patch('/:id',flieUpload(fileType.image).single('image'),validation(schema.updateCategorySchema),auth(endPoint.update),asyncHandler(CtegoryController.update));
router.delete('/:id',validation(schema.deleteCategorySchema),auth(endPoint.delete),asyncHandler(CtegoryController.deleteCategory));
export default router;